server:
  port: 8080
  servlet:
    session:
      timeout: 30m # セッションタイムアウト（30分）

spring:
  application:
    name: ai-sample
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  mail:
    host: localhost
    port: 3025
    username: test@example.com
    password: password
    protocol: smtp
    properties:
      "[mail.smtp.auth]": false
      "[mail.smtp.starttls.enable]": false
    default-encoding: UTF-8
  thymeleaf:
    cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true


app:
  security:
    login:
      attempt:
        max: 5
        lock-duration-ms: 1800000 # 30分
logging:
  level:
    "[io.github.yoshikawaa.example.ai_sample]": DEBUG
    "[io.github.yoshikawaa.example.ai_sample.repository]": INFO
